// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserInitParameters struct {

	// (String) The email of the User to create.
	// The email of the User to create.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) True if the User should be of type local. Defaults to true.
	// `True` if the User should be of type `local`. Defaults to `true`.
	IsLocal *bool `json:"isLocal,omitempty" tf:"is_local,omitempty"`

	// (String) The login name of the User to create. Changing this forces a new resource to be created.
	// The login name of the User to create. Changing this forces a new resource to be created.
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (String) The name of the User to create. Changing this forces a new resource to be created.
	// The name of the User to create. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) The password of User to create. This is only used if the user is of type local.
	// The password of User to create. This is only used if the user is of type `local`.
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`
}

type UserObservation struct {

	// (String) The email of the User to create.
	// The email of the User to create.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) True if the User should be of type local. Defaults to true.
	// `True` if the User should be of type `local`. Defaults to `true`.
	IsLocal *bool `json:"isLocal,omitempty" tf:"is_local,omitempty"`

	// (String) The login name of the User to create. Changing this forces a new resource to be created.
	// The login name of the User to create. Changing this forces a new resource to be created.
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (String) The name of the User to create. Changing this forces a new resource to be created.
	// The name of the User to create. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type UserParameters struct {

	// (String) The email of the User to create.
	// The email of the User to create.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) True if the User should be of type local. Defaults to true.
	// `True` if the User should be of type `local`. Defaults to `true`.
	// +kubebuilder:validation:Optional
	IsLocal *bool `json:"isLocal,omitempty" tf:"is_local,omitempty"`

	// (String) The login name of the User to create. Changing this forces a new resource to be created.
	// The login name of the User to create. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (String) The name of the User to create. Changing this forces a new resource to be created.
	// The name of the User to create. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) The password of User to create. This is only used if the user is of type local.
	// The password of User to create. This is only used if the user is of type `local`.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Provides a Sonarqube User resource. This can be used to manage Sonarqube Users.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonarqube}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loginName) || (has(self.initProvider) && has(self.initProvider.loginName))",message="spec.forProvider.loginName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
