apiVersion: project.sonarqube.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: SonarQube
    project: my_project
    visibility: public
