// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MainBranchInitParameters struct {

	// (String) The name you want the main branch to have.
	// The name you want the main branch to have.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	// +crossplane:generate:reference:type=github.com/smoothglue/provider-sonarqube/apis/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`
}

type MainBranchObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name you want the main branch to have.
	// The name you want the main branch to have.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type MainBranchParameters struct {

	// (String) The name you want the main branch to have.
	// The name you want the main branch to have.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
	// +crossplane:generate:reference:type=github.com/smoothglue/provider-sonarqube/apis/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`
}

// MainBranchSpec defines the desired state of MainBranch
type MainBranchSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MainBranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MainBranchInitParameters `json:"initProvider,omitempty"`
}

// MainBranchStatus defines the observed state of MainBranch.
type MainBranchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MainBranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MainBranch is the Schema for the MainBranchs API. Provides a Sonarqube Project main branch resource. This can be used to create and manage a Sonarqube Projects main branch.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonarqube}
type MainBranch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MainBranchSpec   `json:"spec"`
	Status MainBranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MainBranchList contains a list of MainBranchs
type MainBranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MainBranch `json:"items"`
}

// Repository type metadata.
var (
	MainBranch_Kind             = "MainBranch"
	MainBranch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MainBranch_Kind}.String()
	MainBranch_KindAPIVersion   = MainBranch_Kind + "." + CRDGroupVersion.String()
	MainBranch_GroupVersionKind = CRDGroupVersion.WithKind(MainBranch_Kind)
)

func init() {
	SchemeBuilder.Register(&MainBranch{}, &MainBranchList{})
}
